### ISSUE TITLE
Issue with adding printer

### ISSUE THREAD

**Issue by filipkowicz** [kuzmin-no/Brother_DCP-T426W#1]
Hi, I'm getting following issue when i'm trying to use added driver - i guess it's related to file permissions - do you know how they should be set?
<img width="262" alt="Screenshot 2024-12-03 at 23 24 46" src="https://github.com/user-attachments/assets/2b33037b-5bb0-43e9-a50d-232fdd99c5aa">

**Comment by filipkowicz** [comment]
i guess it might be related to System Integrity Protection since file has xattrs "com.apple.provenance:" which i can't remove

**Comment by kuzmin-no** [comment]
Hi, when I download a file from github.com/Internet it usually has only com.apple.quarantine attribue, which might be deleted with command "xattr -d com.apple.quarantine <filename>". Try to remove com.apple.provenance attribue with the same command "xattr -d com.apple.provenance <filename>"

**Comment by kjeske** [comment]
>  Try to remove com.apple.provenance attribue with the same command "xattr -d com.apple.provenance "
From which file?
